### ISSUE TITLE
Unsafe 1password integration

### ISSUE THREAD

**Issue by SixFive7** [royalapplications/toolbox#60] opened 2023-02-01 17:05 UTC
The current version of the 1password dynamic folder script requires the 1password windows hello and biometric unlock functions to be disabled. This is considered unsafe.
Even more important, the script requires one to save the secret key and master password in the Royal TS script configuration fields. This is considered very insecure and (correctly so) actively advised against by 1Password itself.

With the new version of the 1Password CLI tool these credentials are also not required. If the 1Password desktop app and CLI are installed one can just run `op item list --vault Private` and let 1Password handle all the (secure desktop) prompts for logging in and authorizing the request. Hence the need to store master password credentials inside Royal TS is no longer there.

We should not ask for or store credentials and use the CLI securely and as intended.

**Comment by SixFive7** [comment] 2023-02-01 17:06
Related to https://github.com/royalapplications/toolbox/issues/46?

**Comment by StefanKoell** [comment] 2023-02-02 07:31
I agree, if these options are now available (and reliably working) we should definitely utilize the newest version of the 1Password CLI (also assuming that there are no other downsides/showstoppers)

@SixFive7 would you be able to create a PR and/or test for that?

**Comment by joachimtingvold** [comment] 2023-02-19 20:59
I modified the existing code, removing historic stuff (v1 vs v2 CLI, login/logout, etc). Code reduced by 1/4 of the original. Seems to work for me on my Mac. Have not done extensive testing yet, and untested on Windows. Biometric popup works as expected.

The only limitation (for now) is that it doesn't support multiple 1Password-accounts in the _same_ dynamic folder. Also, the `account` custom property is a required field even if you only have 1 account, and was done to make sure you are fetching credentials from the account you want (in case you have multiple, like I have).

I have not created a PR yet, as I'm not sure if it should be added as a separate script, or modify the existing one (as this script will _only_ work on 1Password v8 or above).

1. Import the existing 1Password dynamic folder script.
2. Replace the script code with the following; https://gist.github.com/joachimtingvold/fef17f2772ebd623b1b1ea4135e1e7f5
3. Remove all of the Login Custom Properties (strictly not needed, but they are not used anymore)
4. Add the `Account` custom property. Use the value from the `USER ID` column from `op account list`.
5. Hit "Apply & Close", right click the dynamic folder, and choose "Reload".

**Comment by jvwam** [comment] 2023-04-24 04:38
@joachimtingvold I've just tested this on Windows and it's working
The `vault` custom property is case-sensitive, not an issue if it's copied directly from `op vault list`

**Comment by jvwam** [comment] 2023-07-26 00:44
@joachimtingvold I've updated your scripts to allow for multiple vaults
In the Custom Properties vault field, add a comma separated list of vaults, otherwise it works the same
I haven't tested this extensively yet but I haven't encountered any issues
https://gist.github.com/jvwam/bd7ebeec596507cb1149a3561c8d43ff

**Comment by sez76** [comment] 2023-08-05 08:54
Hello, in my case it doesn't work

Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'TaskPath') 
 at ikdmg.pkfek(RoyalDynamicFolder ncrlj) in <9pbU/0LjpCexFwUaxM2copsqI6CCCN0x+6Hd3IhFJU1JsDLkQnLDomz/TIZwbEZbNCp1h9g5Fw5mi8/fIsEDaCN6gAqy3SaQ3IcDNn16PElix61Nvkgk/wNIikbYwvSXv3yauZsgmMrqg3nwCLjmyg==>:line 196

**Comment by unreliability** [comment] 2023-08-07 01:35
> 3\. https://gist.github.com/joachimtingvold/fef17f2772ebd623b1b1ea4135e1e7f5

Absolute lifesaver, can confirm this works PERFECTLY after months of trying just about anything to get multi-vault working with 1password 8 + Touch ID, cheers man, just made my evening! Should definitely be PR'd into the main branch!

**Comment by joachimtingvold** [comment] 2023-08-07 09:05
> @joachimtingvold I've updated your scripts to allow for multiple vaults In the Custom Properties vault field, add a comma separated list of vaults, otherwise it works the same I haven't tested this extensively yet but I haven't encountered any issues https://gist.github.com/jvwam/bd7ebeec596507cb1149a3561c8d43ff

Excellent. I updated my gist with your changes, so people get the same result regardless of which gist they find (=

**Comment by elbcloudhh** [comment] 2023-08-07 10:44
Hi guys, this is amazing! Thank you. Would it be possible for the script to get all vaults automatically in a way that we don't have to maintain the vault list?

**Comment by joachimtingvold** [comment] 2023-08-07 21:38
@elbcloudhh, the version in PR #71 solves this.

**Comment by lazynooblet** [comment] 2023-09-07 11:41
@joachimtingvold thanks for your work. Using your PR I have RoyalTS working with 1Password using a dynamic folder and its really really neat.

I also use 1Password SSH agent, so that linux connections get the ssh key automatically. From a user perspective the SSH agent will approve the app (requiring re-auth) for the request and then subsequent requests for the same key are allowed automatically. So I only need to auth once.

With the dynamic folder, I have to re-auth 1Password every time I connect to a server, is there any way for it to cache the credentials for a period or an option in 1Password to allow a similar experience to the SSH agent?

**Comment by joachimtingvold** [comment] 2023-09-07 11:56
I think the problem is that Royal spawns a new iTerm2-process for each window/tab, which from 1Passwords perspective is not the same instance already authenticated. I notice that the 1Password authorization popup explicitly mentions Royal as the app (and not iTerm), so I guess there could be room for improvements in Royal.

**Comment by joachimtingvold** [comment] 2023-09-07 14:17
Actually, come to think of it, I do not need to re-auth to 1Password for each connection. I have to do it at launch, and when opening new connections after a while (i.e. it's been idle, or screensaver has been triggered, etc). Other than that I don't need to authorize in 1Password much.

**Comment by lazynooblet** [comment] 2023-09-12 09:00
I'm not sure why I get a different experience. I get the Windows Hello request on _every_ connection.

![2023-09-12 09_55_57-app nooblet org (root) - Royal TS](https://github.com/royalapplications/toolbox/assets/1316058/f03facf9-5e93-40ff-9579-a777acaf14ba)

- I double click the connection
- Authenticate with Windows Hello
- Right click, duplicate, or double click a different connection
- Authenticate with Windows Hello again

**Comment by lemonmojo** [comment] 2023-11-28 10:42
Closing this now that the new implementation has been merged. If the issue is still present in the new version, please create a new GH issue.

**Closed by lemonmojo** 2023-11-28 10:42 UTC
